[[slot]]
type = "closing"
author = ""
description = ""
name = "Entrega do prêmio Dorneles Treméa/Jean Ferri"
start_at = 2021-10-15T20:10:00-03:00
duration = 50
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/5XN1r7Sf6wM"

[[slot]]
type = "closing"
author = ""
description = "Momento para a comunidade Python brasileira lembrar e homenagear anualmente a(s) pessoa(s) que mais se destacou(aram) na comunidade e o encerramento oficial do evento com a organização de 2021 e a chamada para o evento de 2022"
name = "Encerramento da Python Brasil 2021"
start_at = 2021-10-15T21:00:00-03:00
duration = 30
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/5XN1r7Sf6wM"

[[slot]]
type = "closing"
author = ""
description = ""
name = "Algorave"
start_at = 2021-10-15T22:00:00-03:00
duration = 120
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/0tD2o4vbATE"

[[slot]]
type = "keynote"
author = ""
description = "Cuducos é um dos fundadores da Operação Serenata de Amor, doutor em sociologia, e desenvolvedor na Shopify. Trabalhou com tecnologia cívica em organizações como Banco Mundial e Open Knowledge Brasil."
name = "Eduardo Cuducos"
start_at = 2021-10-15T19:00:00-03:00
duration = 70
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/5XN1r7Sf6wM"

[[slot]]
type = "keynote"
author = ""
description = "Sou formada em análise e desenvolvimento de sistemas, trabalho como Apoio Pedagógico na Escola de Dados da Open Knowledge Brasil. Uma pessoa da exatas com dois pés em humanas.\n"
name = "Anicely Santos"
start_at = 2021-10-12T20:20:00-03:00
duration = 70
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/fXRGok6QbIw"

[[slot]]
type = "keynote"
author = ""
description = "Kizzy e Hallison são criadores do canal Programação Dinâmica no YouTube onde ensinam sobre programação, ciência de dados e interligência artificial e discutem sobre novas tecnologias na sociedade."
name = "Kizzy Terra e Hallison Paz"
start_at = 2021-10-11T20:20:00-03:00
duration = 70
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/ia-W6GwDTto"
    [slot.streaming]
    start_at = 1776
    duration = 4211
    filename = "pybr2021_keynote_kizzy_terra_e_hallison_paz__segundafeira__dia_1110_pybr2021_20211011_195206.mp4"

[[slot]]
type = "keynote"
author = ""
description = "Yaso é Principal Privacy Researcher na Unico IDTech. Trabalhou no Banco Mundial, e colaborou para a integração de tecnologia e inovação na infraestrutura de governança de países em desenvolvimento. Foi CEO do Serenata de Amor e cofundadora do Calango Hackerspace."
name = "Yasodara Córdova "
start_at = 2021-10-13T20:20:00-03:00
duration = 70
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/-OMV8DEEN8E"

[[slot]]
type = "keynote"
author = ""
description = "Co-fundadora do PyLadies Brasil/Natal. Formada em Tecnologia da Informação (UFRN), sou desenvolvedora na Vinta, e estou sempre interessada em conversar sobre Python, Testes e Qualidade de Software."
name = "Gabriela Cavalcante da Silva"
start_at = 2021-10-14T20:20:00-03:00
duration = 70
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/Ul8aA8w7DTw"

[[slot]]
type = "panel"
author = ""
description = ""
name = "AfroPython"
start_at = 2021-10-11T10:00:00-03:00
duration = 120
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/HqRDZ5unNuo"
    [slot.streaming]
    start_at = 798
    duration = 7030
    filename = "pybr2021_abertura__roda_de_conversa_sobre_afropython__segundafeira__dia_1110_pybr2021_20211011_100032.mp4"

[[slot]]
type = "panel"
author = ""
description = ""
name = "Associação Python Brasil"
start_at = 2021-10-12T10:00:00-03:00
duration = 120
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/E78Ye0rQ1uA"
    [slot.streaming]
    start_at = 43
    duration = 7134
    filename = "[PyBr2021] Roda de conversa sobre APyB - Terça-feira - Dia 12_10 #PyBr2021.mp4"


[[slot]]
type = "panel"
author = ""
description = ""
name = "Dados Abertos"
start_at = 2021-10-13T10:00:00-03:00
duration = 120
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/M2H44tQA_b8"

[[slot]]
type = "panel"
author = ""
description = ""
name = "Educação não formal"
start_at = 2021-10-14T10:00:00-03:00
duration = 120
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/4xrgUjNRqK4"

[[slot]]
type = "panel"
author = ""
description = ""
name = "Segurança"
start_at = 2021-10-15T10:00:00-03:00
duration = 120
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/cDoxtv2uwXo"
