[[slot]]
type = "light"
author = "Você!!"
description = ""
name = "Palestras Relâmpago"
start_at = 2021-10-11T19:50:00-03:00
duration = 50
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/ia-W6GwDTto"
    [slot.streaming]
    start_at = 43
    duration = 874
    filename = "[PyBr2021] Keynote_ Kizzy Terra e Hallison Paz - Segunda-feira - Dia 11_10 #PyBr2021.mp4"

[[slot]]
type = "light"
author = "Você!!"
description = ""
name = "Palestras Relâmpago"
start_at = 2021-10-12T19:50:00-03:00
duration = 40
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/fXRGok6QbIw"

[[slot]]
type = "light"
author = "Você!!"
description = ""
name = "Palestras Relâmpago"
start_at = 2021-10-13T19:50:00-03:00
duration = 40
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/-OMV8DEEN8E"

[[slot]]
type = "light"
author = "Você!!"
description = ""
name = "Palestras Relâmpago"
start_at = 2021-10-14T17:30:00-03:00
duration = 70
discord_channel = "893958446909640734"
room = "Angelica Ross"
youtube_channel = "https://youtu.be/PUsjycX4XR0"


[[slot]]
type = "light"
author = "Você!!"
description = ""
name = "Palestras Relâmpago"
start_at = 2021-10-14T19:50:00-03:00
duration = 40
discord_channel = "895487732443389983"
room = ""
youtube_channel = "https://youtu.be/Ul8aA8w7DTw"
